from django.conf.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^project/$', views.report_project, name="report_project"),
    re_path(r'^dashboard/$', views.report_dashboard, name="report_dashboard"),
    re_path(r'^project/edit/$', views.report_project_edit,
            name="report_project_edit"),
    re_path(r'^project/dashboard/$', views.report_project_dashboard,
            name="report_project_dashboard"),
    re_path(r'^maintenance/$', views.report_maintenance,
            name="report_maintenance"),
    re_path(r'^maintenance/dashboard/$', views.report_maintenance_dashboard,
            name="report_maintenance_dashboard"),
    re_path(r'^maintenance/client/$', views.report_maintenance_client,
            name="report_maintenance_client"),
    re_path(r'^maintenance/client/edit/$', views.report_maintenance_client_edit,
            name="report_maintenance_client_edit"),
    re_path(r'^support/$', views.report_support,
            name="report_support"),
    re_path(r'^support/client/edit/$', views.report_support_edit,
            name="report_support_edit"),
    re_path(r'^edu/$', views.report_edu,
            name="report_edu"),
    re_path(r'^edu/client/edit$', views.report_edu_edit,
            name="report_edu_edit"),
    re_path(r'^etc/$', views.report_etc,
            name="report_etc"),
    re_path(r'^etc/client/edit$', views.report_etc_edit,
            name="report_etc_edit"),
]
