# Generated by Django 2.0.13 on 2020-10-15 01:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import document.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '__first__'),
        ('member', '0030_remove_member_pw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, editable=False, null=True)),
                ('kind', models.CharField(choices=[('PRE', 'Presales'), ('PRO', '수행계획서'), ('MAN', '유지보수'), ('EXA', '검수'), ('ETC', '기타')], default='ETC', max_length=3)),
                ('pre_middle_class', models.CharField(blank=True, choices=[('WBS', 'WBS'), ('제안서', '제안서'), ('제품소개서', '제품소개서'), ('계약서', '계약서')], max_length=10, null=True)),
                ('pro_middle_class', models.CharField(blank=True, choices=[('견적서', '견적서'), ('발주서', '발주서'), ('고객사 요구사항', '고객사 요구사항')], max_length=10, null=True)),
                ('exa_middle_class', models.CharField(blank=True, choices=[('검수확인서', '검수확인서'), ('세금계산서', '세금계산서')], max_length=10, null=True)),
                ('man_middle_class', models.CharField(blank=True, choices=[('유지보수 계약서', '유지보수 계약서')], max_length=10, null=True)),
                ('etc_middle_class', models.CharField(blank=True, choices=[('기타', '기타')], max_length=10, null=True)),
                ('comments', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Member')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach', models.FileField(default='', upload_to=document.models._documentattachment_upload_path)),
                ('attach_name', models.CharField(default='', max_length=50)),
                ('content_size', models.CharField(default='', max_length=50)),
                ('content_type', models.CharField(default='', max_length=100)),
                ('check_code', models.CharField(default='', max_length=128)),
                ('is_state', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='document.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('PRO', '프로젝트'), ('MAN', '유지보수'), ('SUP', '지원'), ('EDU', '교육'), ('ETC', '기타')], default='ETC', max_length=10)),
                ('info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Client', verbose_name='the related client')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Member')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Product', verbose_name='the related product')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='document.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('title', 'product')},
        ),
    ]
