# Generated by Django 2.0.13 on 2020-10-15 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='etc_middle_class',
        ),
        migrations.RemoveField(
            model_name='document',
            name='exa_middle_class',
        ),
        migrations.RemoveField(
            model_name='document',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='document',
            name='man_middle_class',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pre_middle_class',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pro_middle_class',
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.RemoveField(
            model_name='project',
            name='info',
        ),
        migrations.RemoveField(
            model_name='project',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='project',
            name='product',
        ),
        migrations.RemoveField(
            model_name='project',
            name='update_at',
        ),
    ]
