# Generated by Django 2.0.13 on 2020-10-16 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '__first__'),
        ('document', '0002_auto_20201015_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('PRE', 'Presales'), ('PRO', '수행계획서'), ('MAN', '유지보수'), ('EXA', '검수'), ('ETC', '기타')], default='PRE', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Client'),
        ),
        migrations.AddField(
            model_name='document',
            name='mnfacture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Mnfacture'),
        ),
        migrations.AddField(
            model_name='document',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Product'),
        ),
        migrations.AddField(
            model_name='document',
            name='product_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.ProductModel'),
        ),
        migrations.AlterField(
            model_name='document',
            name='project',
            field=models.SmallIntegerField(default=0),
        ),
    ]
