# Generated by Django 2.0.13 on 2020-10-16 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0030_remove_member_pw'),
        ('document', '0004_remove_document_product_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='member',
        ),
        migrations.AddField(
            model_name='document',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Member'),
        ),
    ]
