# Generated by Django 2.0.13 on 2020-10-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_auto_20201016_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
