# Generated by Django 2.0.13 on 2020-10-19 06:07

from django.db import migrations, models
import document.models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_project_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='attach',
            field=models.FileField(default='', upload_to=document.models._documentattachment_upload_path),
        ),
        migrations.AddField(
            model_name='document',
            name='attach_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='check_code',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='document',
            name='content_size',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='content_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
