# Generated by Django 2.0.13 on 2020-10-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_auto_20201019_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
