# Generated by Django 2.0.13 on 2020-10-22 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_document_update_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.RemoveField(
            model_name='project',
            name='member',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
