# Generated by Django 2.0.13 on 2020-10-22 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0010_auto_20201022_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='mnfacture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Mnfacture'),
        ),
        migrations.AlterField(
            model_name='document',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Product'),
        ),
    ]
