# Generated by Django 2.0.13 on 2020-10-30 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0011_auto_20201022_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentattachment',
            name='document',
        ),
        migrations.DeleteModel(
            name='DocumentAttachment',
        ),
    ]
