# Generated by Django 2.0.13 on 2020-11-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0012_auto_20201030_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentBasicForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('attach_name', models.CharField(default='', max_length=50)),
                ('content_size', models.CharField(default='', max_length=50)),
                ('content_type', models.CharField(default='', max_length=100)),
                ('check_code', models.CharField(default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
    ]
