# Generated by Django 2.0.13 on 2020-11-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0013_documentbasicform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentbasicform',
            name='comments',
        ),
        migrations.AddField(
            model_name='documentbasicform',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
