# Generated by Django 2.0.13 on 2020-11-02 06:49

from django.db import migrations, models
import document.models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0014_auto_20201102_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentbasicform',
            name='attach',
            field=models.FileField(default='', upload_to=document.models._documentattachment_upload_path),
        ),
    ]
