# Generated by Django 2.0.13 on 2020-03-10 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='makers',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
