# Generated by Django 2.0.13 on 2020-04-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20200310_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mnfacture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manafacture', models.CharField(default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['manafacture'],
            },
        ),
    ]
