# Generated by Django 2.0.13 on 2020-04-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_mnfacture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
