# Generated by Django 2.0.13 on 2020-06-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_product_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(default='', max_length=40, unique=True),
        ),
    ]
