# Generated by Django 2.0.13 on 2020-07-14 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20200624_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='client',
            old_name='similiar_word',
            new_name='similar_word',
        ),
    ]
