# Generated by Django 2.0.13 on 2020-09-08 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_auto_20200714_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mnfacture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Mnfacture'),
        ),
    ]
