# Generated by Django 2.0.13 on 2020-08-10 15:05

from django.db import migrations, models
import django.db.models.deletion
import equipment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0011_auto_20200714_1718'),
        ('member', '0030_remove_member_pw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(default='', max_length=50)),
                ('location', models.CharField(default='', max_length=100)),
                ('install_date', models.DateField(blank=True, max_length=20)),
                ('manager', models.CharField(default='', max_length=50)),
                ('comments', models.CharField(default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Client')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Member')),
                ('mnfacture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Mnfacture')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Product')),
                ('product_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.ProductModel')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach', models.FileField(default='', upload_to=equipment.models._equipmentattachment_upload_path)),
                ('attach_name', models.CharField(default='', max_length=50)),
                ('content_size', models.CharField(default='', max_length=50)),
                ('content_type', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(default='', max_length=50)),
                ('location', models.CharField(default='', max_length=100)),
                ('status', models.CharField(choices=[('keep', 'keep'), ('sold', 'sold')], default='keep', max_length=10)),
                ('receive_date', models.DateField(blank=True, max_length=20)),
                ('comments', models.CharField(default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Member')),
                ('mnfacture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Mnfacture')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Product')),
                ('product_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.ProductModel')),
            ],
        ),
        migrations.CreateModel(
            name='StockAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach', models.FileField(default='', upload_to=equipment.models._equipmentattachment_upload_path)),
                ('attach_name', models.CharField(default='', max_length=50)),
                ('content_size', models.CharField(default='', max_length=50)),
                ('content_type', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Member')),
            ],
        ),
    ]
