# Generated by Django 2.0.13 on 2020-07-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='status',
            field=models.CharField(
                choices=[('keep', 'keep'), ('sold', 'sold')], default='keep', max_length=10),
        ),
    ]
