# Generated by Django 2.0.13 on 2020-08-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='status',
            field=models.CharField(choices=[('keep', 'keep'), ('sold', 'sold'), ('disposal', 'disposal'), ('return', 'return')], default='keep', max_length=10),
        ),
    ]
