# Generated by Django 2.0.13 on 2020-08-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20200813_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='disposal_date',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='return_date',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
    ]
