# Generated by Django 2.0.13 on 2020-04-01 06:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20200401_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='install_date',
            field=models.DateField(blank=True, max_length=20),
        ),
    ]
