# Generated by Django 2.0.13 on 2020-07-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_stock_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='status',
            field=models.CharField(choices=[('keep', 'keep'), ('sold', 'sold')], default='keep', max_length=10),
        ),
    ]
