# Generated by Django 2.0.13 on 2020-08-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_auto_20200814_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='receive_date',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
    ]
