# Generated by Django 2.0.13 on 2020-07-23 07:50

from django.db import migrations, models
import django.db.models.deletion
import equipment.models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0030_remove_member_pw'),
        ('equipment', '0003_auto_20200721_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach', models.FileField(default='', upload_to=equipment.models._equipmentattachment_upload_path)),
                ('attach_name', models.CharField(default='', max_length=50)),
                ('content_size', models.CharField(default='', max_length=50)),
                ('content_type', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Member')),
            ],
        ),
    ]
