# Generated by Django 2.0.13 on 2020-04-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_auto_20200401_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='install_date',
            field=models.DateField(blank=True, max_length=20),
        ),
    ]
