# Generated by Django 2.0.13 on 2020-04-03 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_mnfacture'),
        ('equipment', '0005_auto_20200401_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='mnfacture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Mnfacture'),
        ),
    ]
