# Generated by Django 2.0.13 on 2020-04-03 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0029_auto_20200311_1500'),
        ('equipment', '0006_equipment_mnfacture'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='install_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Member'),
        ),
    ]
