# Generated by Django 2.0.13 on 2020-08-24 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_equipment_maintenance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='product',
        ),
    ]
