# Generated by Django 2.0.13 on 2020-09-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_remove_stock_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('keep', 'keep'), ('sold', 'sold'), ('disposal', 'disposal'), ('return', 'return')], default='keep', max_length=10),
        ),
    ]
