# Generated by Django 2.0.13 on 2020-04-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_equipment_install_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='install_member',
            field=models.CharField(default='', max_length=50),
        ),
    ]
