# Generated by Django 2.0.13 on 2020-06-23 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0030_remove_member_pw'),
        ('equipment', '0008_auto_20200403_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentattachment',
            name='member',
        ),
        migrations.AddField(
            model_name='equipment',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Member'),
        ),
        migrations.AddField(
            model_name='equipmentattachment',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.Equipment'),
        ),
    ]
