# Generated by Django 2.0.13 on 2020-09-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_equipment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('operating', 'operating'), ('disposal', 'disposal'), ('return', 'return')], default='operating', max_length=10),
        ),
    ]
