# Generated by Django 2.0.13 on 2020-06-23 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_auto_20200623_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentattachment',
            name='equipment',
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_attach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.EquipmentAttachment'),
        ),
    ]
