# Generated by Django 2.0.13 on 2020-09-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0010_equipmenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenthistory',
            name='status',
            field=models.CharField(choices=[('ram', 'ram'), ('disposal', 'disposal'), ('return', 'return')], max_length=10),
        ),
    ]
