# Generated by Django 2.0.13 on 2020-06-23 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0030_remove_member_pw'),
        ('equipment', '0010_auto_20200623_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_attach',
        ),
        migrations.AddField(
            model_name='equipmentattachment',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Member'),
        ),
    ]
