# Generated by Django 2.0.13 on 2020-06-25 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_auto_20200623_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='install_member',
            new_name='manager',
        ),
    ]
