# Generated by Django 2.0.13 on 2020-09-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_auto_20200915_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('operating', 'operating'), ('ram', 'ram'), ('disposal', 'disposal'), ('return', 'return')], default='operating', max_length=10),
        ),
    ]
