# Generated by Django 2.0.13 on 2020-06-25 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0030_remove_member_pw'),
        ('equipment', '0012_auto_20200625_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Member'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Client'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='mnfacture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Mnfacture'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Product'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='product_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.ProductModel'),
        ),
    ]
