# Generated by Django 2.0.13 on 2020-07-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0013_auto_20200625_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
