# Generated by Django 2.0.13 on 2020-07-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0014_auto_20200701_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='comments',
            field=models.CharField(default='', max_length=200),
        ),
    ]
