# Generated by Django 2.0.13 on 2020-03-06 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0028_auto_20200306_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnfacture', models.CharField(default='', max_length=30)),
                ('model', models.CharField(default='', max_length=40)),
                ('serial', models.CharField(default='', max_length=40)),
                ('cpu', models.CharField(default='', max_length=100)),
                ('memory', models.CharField(default='', max_length=30)),
                ('harddisk', models.CharField(default='', max_length=30)),
                ('is_where', models.CharField(default='', max_length=30)),
                ('is_state', models.IntegerField(default=1)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('closed', models.DateField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('member_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Assetrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stdate', models.DateField(null=True)),
                ('eddate', models.DateField(null=True)),
                ('member_name', models.CharField(default='', max_length=20)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('comments', models.CharField(default='', max_length=200)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.Asset')),
            ],
        ),
    ]
