# Generated by Django 2.0.13 on 2020-02-12 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0020_auto_20200212_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnfacture', models.CharField(default='', max_length=30)),
                ('model', models.CharField(default='', max_length=40)),
                ('cpu', models.CharField(default='', max_length=30)),
                ('memory', models.CharField(default='', max_length=30)),
                ('harddisk', models.CharField(default='', max_length=30)),
                ('is_where', models.CharField(default='', max_length=30)),
                ('is_state', models.IntegerField(default='', max_length=1)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('closed', models.DateField(blank=True, null=True)),
                ('comments', models.CharField(default='', max_length=200)),
                ('member_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Member')),
            ],
        ),
    ]
