# Generated by Django 2.0.13 on 2020-03-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
