# Generated by Django 2.0.13 on 2020-02-14 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20200212_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='member_name',
            new_name='member_id',
        ),
    ]
