# Generated by Django 2.0.13 on 2020-05-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20200311_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='harddisk',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='is_where',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='memory',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='model',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial',
            field=models.CharField(default='', max_length=50),
        ),
    ]
