# Generated by Django 2.0.13 on 2020-02-14 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20200214_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='member_id',
            new_name='member_name',
        ),
    ]
