# Generated by Django 2.0.13 on 2020-05-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20200520_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='asset',
            name='cpu',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='asset',
            name='harddisk',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='asset',
            name='is_where',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='asset',
            name='memory',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='asset',
            name='mnfacture',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='asset',
            name='model',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial',
            field=models.CharField(default='', max_length=128),
        ),
    ]
