# Generated by Django 2.0.13 on 2020-02-18 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20200214_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assetrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stdate', models.DateField()),
                ('eddate', models.DateField()),
                ('member_id', models.CharField(default='', max_length=20)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('comments', models.CharField(default='', max_length=200)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.Asset')),
            ],
        ),
    ]
