# Generated by Django 2.0.13 on 2020-02-20 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20200220_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='member_id',
            new_name='member_name',
        ),
    ]
