# Generated by Django 2.0.13 on 2020-02-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20200220_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrent',
            name='eddate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='assetrent',
            name='stdate',
            field=models.DateField(null=True),
        ),
    ]
