# Generated by Django 2.0.13 on 2020-02-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_auto_20200227_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='cpu',
            field=models.CharField(default='', max_length=50),
        ),
    ]
