# Generated by Django 2.0.13 on 2020-02-28 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_auto_20200228_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
