# Generated by Django 2.0.13 on 2020-02-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20200212_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_dept',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='member_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='member_title',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
