# -*- coding: utf-8 -*-z
# Generated by Django 2.0.13 on 2020-02-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20200212_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member_age',
        ),
        migrations.AddField(
            model_name='member',
            name='member_num',
            field=models.IntegerField(default=5),
        ),
    ]
