# Generated by Django 2.0.13 on 2020-02-12 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20200212_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member_num',
            new_name='member_age',
        ),
    ]
