# Generated by Django 2.0.13 on 2020-02-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_remove_member_member_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_rank',
            field=models.CharField(choices=[('헤헤', '대리'), ('ㅎㅎ', '사원')], default='대리', max_length=20),
        ),
    ]
