# -*- coding: utf-8 -*-z
# Generated by Django 2.0.13 on 2020-02-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_member_member_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_rank',
            field=models.CharField(choices=[('대리', '대리'), ('사원', '사원')], default='대리', max_length=20),
        ),
    ]
