# Generated by Django 2.0.13 on 2020-02-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_auto_20200212_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_rank',
            field=models.CharField(choices=[('경영자', (('대리', '대리'), ('사원', '사원')))], default='대리', max_length=20),
        ),
    ]
