# -*- coding: utf-8 -*-z
# Generated by Django 2.0.13 on 2020-02-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_auto_20200212_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_rank',
            field=models.CharField(choices=[('이사/임원', (('대표이사', '대표이사'), (('상무',), '상무'), (('이사',), '이사')))], default='대표이사', max_length=20),
        ),
    ]
