# Generated by Django 2.0.13 on 2020-02-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0018_auto_20200212_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
