# -*- coding: utf-8 -*-z
# Generated by Django 2.0.13 on 2020-02-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0021_auto_20200213_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='member',
            name='member_dept',
        ),
        migrations.RemoveField(
            model_name='member',
            name='member_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='member_pw',
        ),
        migrations.AddField(
            model_name='member',
            name='dept',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='pw',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
