# Generated by Django 2.0.13 on 2020-02-14 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0022_auto_20200213_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member_id',
            new_name='member_name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='member_rank',
            new_name='rank',
        ),
    ]
