# Generated by Django 2.0.13 on 2020-02-14 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0023_auto_20200214_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member_name',
            new_name='member_id',
        ),
    ]
