# Generated by Django 2.0.13 on 2020-02-20 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0025_auto_20200220_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member_name',
            new_name='member_id',
        ),
    ]
