# Generated by Django 2.0.13 on 2020-02-28 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0026_auto_20200220_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='rank',
            field=models.CharField(choices=[('이사/임원', (('대표이사', '대표이사'), ('상무', '상무'), ('이사', '이사'))), ('직원', (('부장', '부장'), ('차장', '차장'), ('과장', '과장'), ('대리', '대리'), ('주임', '주임'), ('사원', '사원'))), ('연구소', (('연구소장', '연구소장'), ('책임 연구원', '책임 연구원'), ('선임 연구원', '선임 연구원'), ('전임 연구원', '전임 연구원'), ('주임 연구원', '주임 연구원')))], default='대표이사', max_length=20),
        ),
    ]
