# Generated by Django 2.0.13 on 2020-03-11 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0028_auto_20200306_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['name']},
        ),
    ]
