"""
This file was created to use global variables.
"""

# Assets
STATUS_PERSONAL = 1
STATUS_TEST = 2
STATUS_RENTAL = 3
STATUS_DISPOSAL = 4
STATUS_KEEP = 5

# Sites
PROJECT_STATUS_CLOSED = "C"
PROJECT_STATUS_PROGRESSING = "P"

# Weekly
WEEKLY_STATUS_PRE = 'PRE'
WEEKLY_STATUS_POST = 'POST'
WEEKLY_STATUS_ETC = 'ETC'
WEEKLY_STATUS_MAINTANCE = 'MAINTANCE'
REPORT_PERMISSION_DEFAULT = ('사업본부', '사업부 총괄', '대표이사', '연구소')
REPORT_PERMISSION_EXCEPT = ('대표이사', '연구소')
REPORT_DEFAULT_ID = 51
REPORT_DEFAULT_SELECT = 2

# Sample file id
SAMPLE_FILE_ID = 6
STOCK_SAMPLE_FILE_ID = 5

# Similar word
SIMILAR_WORD_DEFAULT = {"similar": []}

# Stock
STATUS_KEEP = "keep"
STATUS_SOLD = "sold"
STATUS_DISPOSAL = "disposal"
STATUS_RETURN = "return"
STATUS_OPERATING = "operating"
