# Generated by Django 2.0.13 on 2020-10-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('P', 'P'), ('C', 'C')], default='P', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField()),
            ],
        ),
    ]
