# Generated by Django 2.0.13 on 2020-10-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('P', '진행 중'), ('C', '진행 완료')], default='P', max_length=10),
        ),
    ]
