# Generated by Django 2.0.13 on 2020-03-11 06:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0003_auto_20200310_1956'),
        ('member', '0029_auto_20200311_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, editable=False, null=True)),
                ('kind', models.CharField(choices=[('PRE', 'Presales'), ('PRO', 'Project Progressing'), ('EXA', 'Examination'), ('MAN', 'Maintenance'), ('ETC', 'ETC')], default='ETC', max_length=3)),
                ('comments', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Member')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach_name', models.CharField(default='', max_length=50)),
                ('upload_name', models.CharField(default='', max_length=50)),
                ('upload_dir', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, editable=False, null=True)),
                ('status', models.CharField(choices=[('C', 'CLOSED'), ('P', 'PROGRESSING')], default='C', help_text='선택해주세요', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Client', verbose_name='the related client')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.ProductModel', verbose_name='the related model')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Product', verbose_name='the related product')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('title', 'product')},
        ),
    ]
