# Generated by Django 2.0.13 on 2020-03-12 05:38

from django.db import migrations, models
import sites.models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentattachment',
            name='attach',
            field=models.FileField(default='', upload_to=sites.models._documentattachment_upload_path),
        ),
    ]
