# Generated by Django 2.0.13 on 2020-03-16 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_documentattachment_attach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='model',
        ),
    ]
