# Generated by Django 2.0.13 on 2020-03-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_remove_document_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='kind',
            field=models.CharField(choices=[('PRE', ('PRD', '제품소개서')), ('PRO', 'Project Progressing'), ('EXA', 'Examination'), ('MAN', 'Maintenace'), ('ETC', 'ETC')], default='ETC', max_length=1),
        ),
    ]
