# Generated by Django 2.0.13 on 2020-03-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_remove_project_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentattachment',
            old_name='upload_name',
            new_name='content_size',
        ),
        migrations.RenameField(
            model_name='documentattachment',
            old_name='upload_dir',
            new_name='content_type',
        ),
        migrations.AddField(
            model_name='documentattachment',
            name='is_state',
            field=models.IntegerField(default='1', max_length=1),
        ),
    ]
