# Generated by Django 2.0.13 on 2020-03-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_auto_20200309_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='kind',
            field=models.CharField(choices=[('PRE', 'Presales'), ('PRO', 'Project Progressing'), ('EXA', 'Examination'), ('MAN', 'Maintenance'), ('ETC', 'ETC')], default='ETC', max_length=3),
        ),
    ]
