# Generated by Django 2.0.13 on 2020-03-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_auto_20200330_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentattachment',
            name='is_state',
            field=models.SmallIntegerField(default=1),
        ),
    ]
