# Generated by Django 2.0.13 on 2020-03-09 07:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_auto_20200309_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentauth',
            name='document',
        ),
        migrations.AddField(
            model_name='document',
            name='auth',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='DocumentAuth',
        ),
    ]
