# Generated by Django 2.0.13 on 2020-03-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_auto_20200309_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentattachment',
            name='attach',
        ),
        migrations.AddField(
            model_name='documentattachment',
            name='attach_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='documentattachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='documentattachment',
            name='upload_dir',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='documentattachment',
            name='upload_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
