# Generated by Django 3.0.3 on 2020-04-02 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_documentattachment_check_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentattachment',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Document'),
        ),
    ]
