# Generated by Django 2.0.13 on 2020-03-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_auto_20200309_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentattachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
