# Generated by Django 2.0.13 on 2020-05-25 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0029_auto_20200311_1500'),
        ('sites', '0007_auto_20200402_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Member'),
        ),
    ]
