# Generated by Django 2.0.13 on 2020-03-10 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200310_1115'),
        ('sites', '0007_auto_20200309_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='model_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.ProductModel', verbose_name='the related model'),
        ),
    ]
