# Generated by Django 2.0.13 on 2020-03-10 10:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_project_model_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, editable=False, null=True),
        ),
    ]
