# Generated by Django 2.0.13 on 2020-06-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0009_auto_20200525_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='middle_class',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10, null=True),
        ),
    ]
