# Generated by Django 2.0.13 on 2020-03-10 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0009_project_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='sales',
        ),
    ]
