# Generated by Django 2.0.13 on 2020-03-10 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20200310_1956'),
        ('sites', '0010_remove_project_sales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='model_id',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='product_id',
            new_name='product',
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('title', 'product')},
        ),
    ]
