# Generated by Django 2.0.13 on 2020-06-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0010_document_middle_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='middle_class',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10, null=True),
        ),
    ]
