# Generated by Django 2.0.13 on 2020-06-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0011_auto_20200609_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='middle_class',
        ),
        migrations.AddField(
            model_name='document',
            name='etc_middle_class',
            field=models.CharField(blank=True, choices=[('A', 'WBS'), ('B', '제안서'), ('C', '제품소개서'), ('D', '계약서')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='exa_middle_class',
            field=models.CharField(blank=True, choices=[('A', 'WBS'), ('B', '제안서'), ('C', '제품소개서'), ('D', '계약서')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='man_middle_class',
            field=models.CharField(blank=True, choices=[('A', 'WBS'), ('B', '제안서'), ('C', '제품소개서'), ('D', '계약서')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='pre_middle_class',
            field=models.CharField(blank=True, choices=[('A', 'WBS'), ('B', '제안서'), ('C', '제품소개서'), ('D', '계약서')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='pro_middle_class',
            field=models.CharField(blank=True, choices=[('A', 'WBS'), ('B', '제안서'), ('C', '제품소개서'), ('D', '계약서')], max_length=10, null=True),
        ),
    ]
