# Generated by Django 2.0.13 on 2020-07-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0012_auto_20200611_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='etc_middle_class',
            field=models.CharField(blank=True, choices=[('기타', '기타')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='exa_middle_class',
            field=models.CharField(blank=True, choices=[('검수확인서', '검수확인서'), ('세금계산서', '세금계산서')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='man_middle_class',
            field=models.CharField(blank=True, choices=[('유지보수 계약서', '유지보수 계약서')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='pre_middle_class',
            field=models.CharField(blank=True, choices=[('WBS', 'WBS'), ('제안서', '제안서'), ('제품소개서', '제품소개서'), ('계약서', '계약서')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='pro_middle_class',
            field=models.CharField(blank=True, choices=[('견적서', '견적서'), ('발주서', '발주서'), ('고객사 요구사항', '고객사 요구사항')], max_length=10, null=True),
        ),
    ]
