# Generated by Django 2.0.13 on 2020-04-07 04:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0004_mnfacture'),
        ('member', '0029_auto_20200311_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_manager', models.CharField(default='', max_length=50)),
                ('sales_type', models.CharField(choices=[('PRE', 'PRESALES'), ('POST', 'POSTSALES'), ('ETC', 'ETC')], default='PRE', help_text='선택해주세요', max_length=4)),
                ('support_comment', models.CharField(default='', max_length=200)),
                ('support_date', models.DateField(default=datetime.datetime.now)),
                ('comments', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Client')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
            options={
                'ordering': ['client'],
            },
        ),
    ]
