# Generated by Django 2.0.13 on 2020-04-07 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0002_auto_20200407_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Client'),
        ),
        migrations.AlterField(
            model_name='report',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
    ]
