# Generated by Django 2.0.13 on 2020-04-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0004_report_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='sales_type',
            field=models.CharField(choices=[('PRE', 'PRESALES'), ('POST', 'POSTSALES'), ('ETC', 'ETC'), ('MAINTANCE', 'MAINTANCE')], default='PRE', help_text='선택해주세요', max_length=10),
        ),
    ]
