# Generated by Django 2.0.13 on 2020-04-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0005_auto_20200423_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='comments',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='report',
            name='sales_type',
            field=models.CharField(choices=[('PRE', 'PRESALES'), ('POST', 'POSTSALES'), ('MAINTANCE', 'MAINTANCE'), ('ETC', 'ETC')], default='PRE', help_text='선택해주세요', max_length=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='support_comment',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
